-- Medhat Stocks private portfolio storage
create table if not exists public.portfolio_positions (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  symbol text not null,
  qty numeric not null check (qty >= 0),
  avg numeric not null check (avg >= 0),
  updated_at timestamptz not null default now(),
  unique(owner_id, symbol)
);

create index if not exists portfolio_positions_owner_idx
  on public.portfolio_positions(owner_id);

alter table public.portfolio_positions enable row level security;

-- The app uses the server-side Supabase service-role key, so no public policy
-- is needed. Never expose the service-role key to the browser/client.
