-- Medhat Stocks private portfolio storage
-- Run once in Supabase SQL Editor.
create table if not exists public.portfolio_positions (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  symbol text not null,
  qty numeric not null check (qty >= 0),
  avg numeric not null check (avg >= 0),
  updated_at timestamptz not null default now(),
  unique(owner_id, symbol)
);

create index if not exists portfolio_positions_owner_idx
  on public.portfolio_positions(owner_id);

alter table public.portfolio_positions enable row level security;

-- Transaction history: purchases/sales are recorded separately so the app can
-- calculate the current position and weighted average cost without manual edits.
create table if not exists public.portfolio_transactions (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  symbol text not null,
  side text not null check (side in ('buy','sell')),
  qty numeric not null check (qty > 0),
  price numeric not null check (price > 0),
  executed_at timestamptz not null default now(),
  note text
);

create index if not exists portfolio_transactions_owner_idx
  on public.portfolio_transactions(owner_id, executed_at desc);

alter table public.portfolio_transactions enable row level security;

-- The Streamlit/Telegram server uses the Supabase service-role key.
-- Never expose that key to browser-side code.